### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#320]
I tried, but I'm stuck here:

```
> tc-project@0.0.0 build /home/a/work/tc
> gulp build

[11:32:52] Using gulpfile ~/work/tc/gulpfile.js
[11:32:52] Starting 'build'...
(node:15048) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)
Hash: e0dec9022e71bc903eb1daf9347cf9653f71fe87
Version: webpack 1.12.15
Child
    Hash: e0dec9022e71bc903eb1
    Version: webpack 1.12.15
    Time: 6663ms
      Asset     Size  Chunks             Chunk Names
    main.js  22.1 kB       0  [emitted]  main.js
        + 13 hidden modules
Child
    Hash: daf9347cf9653f71fe87
    Version: webpack 1.12.15
    Time: 8547ms
          Asset     Size  Chunks             Chunk Names
    renderer.js  5.86 MB       0  [emitted]  renderer.js
        + 517 hidden modules
    
    WARNING in ./src/~/ws/lib/BufferUtil.js
    Module not found: Error: Cannot resolve module 'bufferutil' in /home/a/work/tc/src/node_modules/ws/lib
     @ ./src/~/ws/lib/BufferUtil.js 10:19-40
    
    WARNING in ./src/~/ws/lib/Validation.js
    Module not found: Error: Cannot resolve module 'utf-8-validate' in /home/a/work/tc/src/node_modules/ws/lib
     @ ./src/~/ws/lib/Validation.js 10:19-44

> tc-project@0.0.0 dist /home/a/work/tc
> build

(node:15085) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for platform linux x64 using electron 1.4.12 to dist/linux-unpacked

Error: Command failed: /home/a/.cache/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/a/work/tc/dist/Tc-6.1.0-x86_64.AppImage -padding 0 -map /home/a/work/tc/dist/linux-unpacked /usr/bin -map /home/a/work/tc/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-TLP6rT/temp-0-Tc.desktop /Tc.desktop -move /usr/bin/Tc /usr/bin/Tc -chmod +x /AppRun /usr/bin/Tc -- -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_16x16x32.png /usr/share/icons/default/16x16/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_24x24x32.png /usr/share/icons/default/24x24/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_32x32x32.png /usr/share/icons/default/32x32/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_48x48x32.png /usr/share/icons/default/48x48/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_64x64x32.png /usr/share/icons/default/64x64/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_96x96x32.png /usr/share/icons/default/96x96/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_128x128x32.png /usr/share/icons/default/128x128/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_256x256x32.png /usr/share/icons/default/256x256/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_512x512x32.png /usr/share/icons/default/512x512/apps/Tc.png -map /tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Drive current: -dev '/home/a/work/tc/dist/Tc-6.1.0-x86_64.AppImage'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 16.4g free
New volume id: 'AppImage'
xorriso : UPDATE : 71 files added in 1 seconds
Added to ISO image: directory '/usr/bin'='/home/a/work/tc/dist/linux-unpacked'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/AppRun'='/home/a/work/tc/node_modules/electron-builder/templates/linux/AppRun.sh'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/Tc.desktop'='/tmp/electron-builder-TLP6rT/temp-0-Tc.desktop'
xorriso : WARNING : Ignored attempt to rename '/usr/bin/Tc' to itself
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/16x16/apps/Tc.png'='/tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_16x16x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/24x24/apps/Tc.png'='/tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_24x24x32.png'
xorriso : FAILURE : Cannot determine attributes of source file '/tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_32x32x32.png' : No such file or directory
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Drive current: -dev '/home/a/work/tc/dist/Tc-6.1.0-x86_64.AppImage'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 16.4g free
New volume id: 'AppImage'
xorriso : UPDATE : 71 files added in 1 seconds
Added to ISO image: directory '/usr/bin'='/home/a/work/tc/dist/linux-unpacked'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/AppRun'='/home/a/work/tc/node_modules/electron-builder/templates/linux/AppRun.sh'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/Tc.desktop'='/tmp/electron-builder-TLP6rT/temp-0-Tc.desktop'
xorriso : WARNING : Ignored attempt to rename '/usr/bin/Tc' to itself
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/16x16/apps/Tc.png'='/tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_16x16x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/24x24/apps/Tc.png'='/tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_24x24x32.png'
xorriso : FAILURE : Cannot determine attributes of source file '/tmp/electron-builder-TLP6rT/temp-1-electron-builder-linux/icon_32x32x32.png' : No such file or directory
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

    at /home/a/work/tc/node_modules/electron-builder/src/util/util.ts:96:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at Object.exec (/home/a/work/tc/node_modules/electron-builder/src/util/util.ts:77:3)
    at AppImageTarget.<anonymous> (/home/a/work/tc/node_modules/electron-builder/src/targets/appImage.ts:64:15)
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at tsAwaiter (/home/a/work/tc/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/home/a/work/tc/node_modules/electron-builder/out/builder.js:135:12)
    at Object.<anonymous> (/home/a/work/tc/node_modules/electron-builder/out/build-cli.js:23:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tc-project@0.0.0 dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the tc-project@0.0.0 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tc-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tc-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tc-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/a/work/tc/npm-debug.log
mv: no such file or directory: dist/win/**
mv: no such file or directory: dist/mac/*.dmg
mv: no such file or directory: dist/mac/*.zip
[11:33:04] Finished 'build' after 12 s

Process finished with exit code 0

```

I don't understand why it's failing at the 32x32 icon yet 16 and 24 are fine...

**Comment by scsddeputy** [comment]
it might be an issue with the version of electron-builder you're using. In the package.json you're using v6.4 but its up to 11.something now, try updating the builder.

**Comment by mccxiv** [comment]
Yeah I did try that as well, same error

**Comment by scsddeputy** [comment]
it actually appears to be an issue with builder, there are a few issues that were opened on their repo: https://github.com/electron-userland/electron-builder/issues/1115

**Comment by scsddeputy** [comment]
so i have been working on getting a working build on linux working and i think i have finally found a solution, but with a few slight complications. Once i get it building proper ill make a PR

**Comment by scsddeputy** [comment]
@mccxiv to get this working, the builder has to be updated to the latest version and the package.json file is going to have to be modified a lot. If this is something that you dont want done let me know, im still working on getting a pr made that will work on linux and windows, dont have a mac image installed on my pc anymore so you might have to do the testing for it

**Comment by mccxiv** [comment]
Sweet, send it in and I'll test it on all platforms 🎉

**Comment by scsddeputy** [comment]
okay, ill submit the pr when its ready

**Comment by scsddeputy** [comment]
found a way to build linux package without having to update everything, instead just have to shuffle things around a bit. Submitting PR in just a few mins

**Comment by scsddeputy** [comment]
#325 Fixes this issue

**Comment by Kerrick** [comment]
Let me know if there's anything I can do to help. I'm a JavaScript developer and long-time TC user on Mac OS, and I just got an Ubuntu laptop. Would be glad to help!

**Comment by mccxiv** [comment]
Thanks @Kerrick I want to review #325 today and see what's left to do for this issue

**Comment by mccxiv** [comment]
Done
